### ISSUE TITLE
build lib issue with angular 7

### ISSUE THREAD

**Issue by ash4aque** [juristr/ngx-tabs-libdemo#15]
After upgrading angular to 7.2.9, npm run build:lib gives following error?

![image](https://user-images.githubusercontent.com/3627868/61714059-95f3b100-ad77-11e9-8a24-ee31b29c143c.png)

**Comment by juristr** [comment]
🤔 I'd have to check but am currently a bit short on time. This repo was actually just a demo repo for my talk I gave a while back.

Which branch are you on?

**Comment by ash4aque** [comment]
I am on `multi-lib-monorepo`.

**Comment by juristr** [comment]
oh yes, that branch would definitely need some updating. I was using nx.dev in there, meanwhile they built this functionality in. You can read more on https://nx.dev or here https://nx.dev/angular/tutorial/08-create-libs

you can check it out in this repo where I'm currently experimenting with assume stuff https://github.com/juristr/ngx-lazy-el
