### ISSUE TITLE
Rsync selecting node_modules

### ISSUE THREAD

**Issue by Karasuni** [juristr/ngx-tabs-libdemo#2]
https://github.com/juristr/ngx-tabs-libdemo/blob/0bfd78440d9c310d504b4e355d569dd5c5ac0e6a/package.json#L12

Does this line not also search and copy files from `node_modules`?

**Comment by juristr** [comment]
🤔 hmm...could actually be.

But anyways, the latest version in the master branch has been migrated to use ng-packagr for distributing the library. There in the README is also the link to the branch containing the “manual-setup” I demoed at the NG-BE conference talk. But I've removed rsync as it's not cross OS and replaced it with copyfiles
